### PR TITLE
A few new goals and goal statistics

### PR DESCRIPTION
**Pull request by DLu**
Plus a couple of bug fixes.

### CODE REVIEW

**Comment by DLu** [comment]
All comments addressed!

**Comment by DLu** [comment]
More comments addressed!

**Comment by rrenaud** [comment]
I am ready to merge this, but it won't apply cleanly.  Can you pull sync back to my repo?

**Comment by rrenaud** [comment]
Also, do you have the command handy to just update the new goals you added, or should I re-run goals.py with --noincremental?

**Comment by DLu** [comment]
Should be all set. 
python goals.py --goals OneTrickPony BuzzerBeater TheFlash SilkTrader Bully PrizeFighter ChampionPrizeFighter Banker ActionStar MegaActionStar SuperActionStar

(all the goals I modified or added)

**Pull request merged**
