### PR TITLE
Pretty CSS for Player Pages

### PR DESCRIPTION
**Pull request by DLu**
http://gonzo.probablydavid.com:8080/player?player=rrenaud

### CODE REVIEW

**Comment by rrenaud** [comment]
While the font used for the councilroom banner is nice for the chrome, I don't like it much for the content.  It's not particularly easy to read when it's small.

Can you make the whole game blob clickable, rather than just the image icon?  If I click on the date, I intend to go to the game page just as much as if I clicked on the image.

Can we pre-expand some of the games for each goal? It wasn't obvious to me that I could click on the goal name to get the expanded of games that met the goal.  Maybe preexpand to length say, 5, and then have a "more" icon (maybe an arrow) that expands the full list.

If you want to be more aggressive, I'd happily see the massive game lists for each player disappear.  Maybe records against common opponents with a link that goes to a search page with all the games against that player would be good.  This would then free up space to just plop the popular buys data onto the player page, which is much more interesting.

**Comment by DLu** [comment]
On Tue, Oct 18, 2011 at 2:16 AM, Rob Renaud <
reply@reply.github.com>wrote:

> While the font used for the councilroom banner is nice for the chrome, I
> don't like it much for the content.  It's not particularly easy to read when
> it's small.

Are you ok with keeping  it for the section headings (like on the main
page)?

> Can you make the whole game blob clickable, rather than just the image
> icon?  If I click on the date, I intend to go to the game page just as much
> as if I clicked on the image.
> 
> Done.
> 
> Can we pre-expand some of the games for each goal? It wasn't obvious to me
> that I could click on the goal name to get the expanded of games that met
> the goal.  Maybe preexpand to length say, 5, and then have a "more" icon
> (maybe an arrow) that expands the full list.
> 
> I implemented that.
> http://gonzo.probablydavid:8080/player?player=hawaiian+shirtshttp://localhost:8080/player?player=hawaiian+shirts
> (I
> didn't implement a more button yet, but it's still clickable)
> However, I think it looks a little funny, especially with the singletons.
> What do you think?

**Comment by rrenaud** [comment]
I can't see the new version, nor your new commits.

**Comment by DLu** [comment]
I didn't commit yet, but meant for you to check out the version running on
my server. http://gonzo.probablydavid:8080/player?player=hawaiian+shirts

**Comment by rrenaud** [comment]
Your demo link has been down both times I've tried in the last day.

**Comment by rrenaud** [comment]
The funny font for the headings is fine.

I agree the singletons look weird.

If you want to the revert pre-expansion, that's fine with me.

**Pull request merged**
