### PR TITLE
pep 8 refactor first cut

### PR DESCRIPTION
**Pull request by robdennis**
This is hopefully not too much to really parse out. This wiki page has been my working scratch pad for what I'm looking for: https://github.com/rdennis463/dominionstats/wiki/pep8-refactoring

So this has been tested with the existing unittest files. All pass except stats test, which was actually failing in my initial checkout as well, with the following output:
# 
## FAIL: testSimple (test_stats.RandomVariableStat)

Traceback (most recent call last):
  File "/Users/rdennis/Documents/Development/dominionstats/test_stats.py", line 15, in testSimple
    self.assertEquals(d.Mean(), 10)
AssertionError: 7.0 != 10

---

Ran 93 tests in 0.434s

### CODE REVIEW

**Comment by rrenaud** [comment]
I am pretty sure this is all now merged into my tree and also running live on councilroom.com without problems (but github didn't auto close for some reason?).  Please close if this is to your satisifaction.

**Comment by robdennis** [comment]
Awesome! :) with this close I was considering implementing some basic
assists for setting up a test database to support the local frontend
and testing

On Apr 30, 2011, at 3:40 AM, rrenaud
reply@reply.github.com
wrote:

**Comment by rrenaud** [comment]
What is a testing assist?

**Comment by robdennis** [comment]
As part of the refactor, I made changes to the player page HTML
rendering. I was never able to test that since there were no players
in my local DB. I'd like to be able to test that in the future. So a
test assist in this Cade us work that supports more formalized testing

On Apr 30, 2011, at 8:15 PM, rrenaud
reply@reply.github.com
wrote:

**Comment by rrenaud** [comment]
I added a small set of testing documents and a script to import them into your a running copy of the database.

If you pull from me, and then run testing/import_sample.py (needs to run from the dominionstats base dir), you should have a database running with a few hundred documents

**Comment by rrenaud** [comment]
I fixed a small problem with the pep8 refactor.  For better or worse, some of the .html files have Python code in them.  For example, here:

https://github.com/rrenaud/dominionstats/commit/7264275ac948ad0e48e549be485819c43c2a829c#buy_template.html

**Comment by robdennis** [comment]
ok, I took a look as to why this didn't close automatically. On the commit list, I don't see the changes with my username as author, which may imply that you checked my code out and manually copied them in, etc. That wouldn't really count as accepting the pull request, since you made a 'different' commit with the same changes as I was offering. So the pull request doesn't know that it should close.

I'm not a github expert either, but I read up on it here: http://help.github.com/pull-requests/
as a bonus, it explains how to send me (instead of rspeer) a pull request

**Pull request closed without merging**
